"""Serve's contract for the plugin's clients. Generated by coordination/cmd/openapi from
coordination/api/openapi.json; do not edit. Regenerate: cd coordination && go run ./cmd/openapi"""
import typing
import urllib.parse

# AccessDTO is GET /api/v1/access: the teams and collaborations a signed-in person may select. It
# carries no membership role. A team's recovery epoch is the tenant's own, so it sits on the team.
AccessDTO = typing.TypedDict("AccessDTO", {
    "v": "int",
    "teams": "list[TeamDTO] | None",
    "collaborations": "list[CollaborationDTO] | None",
    "subject_binding": "str",
    "invitations": "list[InvitationDTO] | None",
})

TeamDTO = typing.TypedDict("TeamDTO", {
    "id": "str",
    "name": "str",
    "recovery_epoch": "str",
    "owner": "bool",
    "workspaces": "list[WorkspaceDTO] | None",
})

# WorkspaceDTO's id is the /w/<alias> route; repo is the workspace's name.
WorkspaceDTO = typing.TypedDict("WorkspaceDTO", {
    "id": "str",
    "team_id": "str",
    "repo": "str",
    "state": "str",
})

CollaborationDTO = typing.TypedDict("CollaborationDTO", {
    "collaborator": "str",
    "workspace": "str",
    "room_grants": "list[RoomGrantDTO] | None",
    "board": "bool",
})

RoomGrantDTO = typing.TypedDict("RoomGrantDTO", {
    "room": "str",
    "rights": "str",
    "expires_at": "str",
})

# InvitationDTO is an open invitation naming the caller's verified GitHub id, which they may redeem.
InvitationDTO = typing.TypedDict("InvitationDTO", {
    "id": "str",
    "kind": "str",
    "team_id": "str",
    "team_name": "str",
    "expires_at": "str",
})

# NeedRaiseBody is a session's need to the owner (EL4 decision 7): an ask, offering options when
# it has choices, or a recommendation, whose question is its proposal and which offers none.
NeedRaiseBody = typing.TypedDict("NeedRaiseBody", {
    "kind": "str",
    "card": "typing.NotRequired[str]",
    "question": "str",
    "context": "typing.NotRequired[str]",
    "options": "typing.NotRequired[list[NeedOptionDTO] | None]",
    "multi": "typing.NotRequired[bool]",
    "allow_other": "typing.NotRequired[bool]",
})

# NeedTransitionBody moves or closes a need (EL4 decision 7): promote, return, dispose or dismiss
# with a reason, or answer an ask with the labels it offered that were chosen and the owner's own
# words where the ask allows them.
NeedTransitionBody = typing.TypedDict("NeedTransitionBody", {
    "kind": "str",
    "reason": "typing.NotRequired[str]",
    "choices": "typing.NotRequired[list[str] | None]",
    "text": "typing.NotRequired[str]",
})

# RulingTransitionBody acknowledges a ruling the seat made on the owner's behalf, or corrects it.
RulingTransitionBody = typing.TypedDict("RulingTransitionBody", {
    "kind": "str",
    "text": "typing.NotRequired[str]",
})

# NeedDTO is a need as the wire answers it, its audience `owner` or `seat`. Session and Epoch name
# who raised it, absent for a need the system raised; Promoted is why the seat handed it to the
# owner, when it did.
NeedDTO = typing.TypedDict("NeedDTO", {
    "id": "str",
    "kind": "str",
    "audience": "str",
    "session": "typing.NotRequired[str]",
    "epoch": "typing.NotRequired[int | None]",
    "card": "typing.NotRequired[str]",
    "question": "str",
    "context": "str",
    "options": "list[NeedOptionDTO] | None",
    "multi": "bool",
    "allow_other": "bool",
    "at": "str",
    "state": "str",
    "promoted": "typing.NotRequired[NeedPromoted | None]",
    "ruling": "typing.NotRequired[str]",
    "return": "typing.NotRequired[NeedReturn | None]",
})

NeedOptionDTO = typing.TypedDict("NeedOptionDTO", {
    "label": "str",
    "description": "typing.NotRequired[str]",
    "recommended": "typing.NotRequired[bool]",
})

NeedPromoted = typing.TypedDict("NeedPromoted", {
    "reason": "str",
    "at": "str",
})

# NeedReturn is the directive an answer went back to its asker as, and its state.
NeedReturn = typing.TypedDict("NeedReturn", {
    "directive": "str",
    "state": "str",
})

# RulingDTO is a ruling as the wire answers it: the owner's own, or the seat's on their behalf, with
# its reason, and whether the owner has acknowledged it.
RulingDTO = typing.TypedDict("RulingDTO", {
    "id": "str",
    "card": "typing.NotRequired[str]",
    "need": "typing.NotRequired[str]",
    "text": "str",
    "reason": "typing.NotRequired[str]",
    "by": "WorkActor",
    "at": "str",
    "on_behalf": "bool",
    "acknowledged": "bool",
})

# NeedAnswer and RulingAnswer are a need's or a ruling's command answer, as IntentAnswer is.
NeedAnswer = typing.TypedDict("NeedAnswer", {
    "need": "NeedDTO",
    "replayed": "bool",
    "position": "int",
})

RulingAnswer = typing.TypedDict("RulingAnswer", {
    "ruling": "RulingDTO",
    "replayed": "bool",
    "position": "int",
})

# NeedList is the needs raised to an audience, and RulingList the unacknowledged rulings, oldest first.
NeedList = typing.TypedDict("NeedList", {
    "needs": "list[NeedDTO] | None",
})

RulingList = typing.TypedDict("RulingList", {
    "rulings": "list[RulingDTO] | None",
})

# Authorities answers the plugin's connect and install which repository the workspace its door
# names is, and which plugin release the orchestrator runs, in the incumbent's shape.
Authorities = typing.TypedDict("Authorities", {
    "primary": "str",
    "release": "typing.NotRequired[str]",
    "authorities": "list[Authority] | None",
    "coordination": "bool",
})

# Authority is one workspace and its repository, as owner/name.
Authority = typing.TypedDict("Authority", {
    "id": "str",
    "repo": "str",
})

# AgentTarget is GET /w/{workspace}/steering/agent/target: the agent release the door tells its
# machines to run, whose package install checks against its digest and size (doc 147 §3).
AgentTarget = typing.TypedDict("AgentTarget", {
    "sha": "str",
    "digest": "str",
    "bytes": "int",
    "pending": "bool",
})

# SeatAcquisition is the body of POST /sessions/{session}/seat/acquisition: the vacancy the
# candidate saw.
SeatAcquisition = typing.TypedDict("SeatAcquisition", {
    "vacancy_generation": "int",
})

# SeatHandover is the body of POST /sessions/{session}/seat/handover: the generation the holder
# holds and the session, at its epoch, that takes the seat.
SeatHandover = typing.TypedDict("SeatHandover", {
    "generation": "int",
    "to": "str",
    "to_epoch": "int",
})

# SeatGeneration is the body of a renewal or a release: the generation the caller holds.
SeatGeneration = typing.TypedDict("SeatGeneration", {
    "generation": "int",
})

# SeatAppointment is the body of POST /seat/appointment: the session, at its epoch, a member seats.
SeatAppointment = typing.TypedDict("SeatAppointment", {
    "to": "str",
    "to_epoch": "int",
})

# DirectiveIssue is the body of POST /sessions/{session}/directives. ID is the directive's
# identity, minted by its issuer.
DirectiveIssue = typing.TypedDict("DirectiveIssue", {
    "id": "str",
    "to": "str",
    "to_epoch": "int",
    "generation": "int",
    "body": "str",
})

# NameClaim is the body of POST /names.
NameClaim = typing.TypedDict("NameClaim", {
    "key": "str",
})

# SeatView is GET /seat: Holder is the session holding it, or nil when it is vacant.
SeatView = typing.TypedDict("SeatView", {
    "holder": "str | None",
    "epoch": "int",
    "generation": "int",
    "vacancy_generation": "int",
    "expires_at": "str | None",
})

# SeatAnswer is a seat command's answer.
SeatAnswer = typing.TypedDict("SeatAnswer", {
    "status": "str",
})

# DirectiveAnswer is an issued directive's answer.
DirectiveAnswer = typing.TypedDict("DirectiveAnswer", {
    "id": "str",
    "status": "str",
})

# NameAnswer is a name claim's answer.
NameAnswer = typing.TypedDict("NameAnswer", {
    "key": "str",
    "status": "str",
})

# CheckpointBody is a session's checkpoint at a boundary of its work (doc 154 §5): its client's
# occurrence, the card it executes when it names one, the boundary, the note it posted and the note's
# digest as the client read it, and what it learned.
CheckpointBody = typing.TypedDict("CheckpointBody", {
    "occurrence": "str",
    "card": "typing.NotRequired[str]",
    "boundary": "str",
    "note": "str",
    "note_sha256": "str",
    "learned": "typing.NotRequired[list[LessonBody] | None]",
})

# LessonBody is one thing a checkpoint learned, and the repository paths it applies to.
LessonBody = typing.TypedDict("LessonBody", {
    "text": "str",
    "scope": "list[str] | None",
})

# CheckpointDTO is a checkpoint as the wire answers it. Current says it is its session's latest at
# its epoch with no acknowledgement since; Dropped counts lessons ingress redacted and left out.
CheckpointDTO = typing.TypedDict("CheckpointDTO", {
    "id": "str",
    "session": "str",
    "epoch": "int",
    "occurrence": "str",
    "card": "typing.NotRequired[str]",
    "boundary": "str",
    "note": "str",
    "note_sha256": "str",
    "learned": "list[LessonBody] | None",
    "dropped": "int",
    "at": "str",
    "current": "bool",
})

# CheckpointAnswer is a checkpoint write's answer.
CheckpointAnswer = typing.TypedDict("CheckpointAnswer", {
    "checkpoint": "CheckpointDTO",
    "replayed": "bool",
    "position": "int",
})

# CheckpointList is a card's checkpoints, oldest first.
CheckpointList = typing.TypedDict("CheckpointList", {
    "checkpoints": "list[CheckpointDTO] | None",
})

# CollaboratorSelf is a collaborator's own reach in one workspace: who it is shown as, and what its
# live grants there open.
CollaboratorSelf = typing.TypedDict("CollaboratorSelf", {
    "collaborator": "str",
    "name": "str",
    "title": "str | None",
    "workspace": "str",
    "room_grants": "list[RoomGrantDTO] | None",
    "board": "bool",
})

# SharedBoard is the board as a board grant shows it: the lanes and their live cards.
SharedBoard = typing.TypedDict("SharedBoard", {
    "lanes": "list[SharedLane] | None",
    "off_track": "SharedLane",
})

SharedLane = typing.TypedDict("SharedLane", {
    "name": "str",
    "cards": "CardTally",
    "live": "list[SharedCard] | None",
})

SharedCard = typing.TypedDict("SharedCard", {
    "id": "str",
    "name": "str",
    "major": "bool",
    "executing": "bool",
    "waiting": "bool",
    "deps": "list[SharedDep] | None",
})

SharedDep = typing.TypedDict("SharedDep", {
    "on": "str",
    "open": "bool",
})

# CollaboratorList is a team's collaborators as its members manage them, each with every grant it
# was given, live or ended.
CollaboratorList = typing.TypedDict("CollaboratorList", {
    "collaborators": "list[CollaboratorDTO] | None",
})

CollaboratorDTO = typing.TypedDict("CollaboratorDTO", {
    "id": "str",
    "name": "str",
    "title": "str | None",
    "disabled": "str | None",
    "grants": "list[CollaborationGrantDTO] | None",
})

CollaborationGrantDTO = typing.TypedDict("CollaborationGrantDTO", {
    "id": "str",
    "workspace_id": "str",
    "workspace_name": "str",
    "scope": "str",
    "room": "str | None",
    "rights": "str",
    "expires_at": "str",
    "revoked": "str | None",
})

# CollaboratorCreateBody makes a collaborator of the team.
CollaboratorCreateBody = typing.TypedDict("CollaboratorCreateBody", {
    "name": "str",
    "title": "str | None",
})

# CollaboratorTitleBody sets a collaborator's title, or clears it with null.
CollaboratorTitleBody = typing.TypedDict("CollaboratorTitleBody", {
    "title": "str | None",
})

# CollaborationGrantBody grants reach in one of the team's workspaces, named by its alias: a room
# to read or post in, or the board to read.
CollaborationGrantBody = typing.TypedDict("CollaborationGrantBody", {
    "workspace": "str",
    "scope": "str",
    "room": "str | None",
    "rights": "str",
    "expires_at": "str",
})

# CollaborationNarrowBody lowers a grant's rights to read or brings its expiry closer: one of them.
CollaborationNarrowBody = typing.TypedDict("CollaborationNarrowBody", {
    "rights": "str | None",
    "expires_at": "str | None",
})

# CollaborationEndBody is why a grant is revoked or a collaborator disabled.
CollaborationEndBody = typing.TypedDict("CollaborationEndBody", {
    "reason": "str",
})

# CollaborationAnswer is a member's collaboration command's answer: what it made or changed, and
# whether it was a retry answered from the first attempt.
CollaborationAnswer = typing.TypedDict("CollaborationAnswer", {
    "id": "str",
    "replayed": "bool",
})

# ConnectableCollaborator is a collaborator a member may connect an assistant as, in a team of theirs.
ConnectableCollaborator = typing.TypedDict("ConnectableCollaborator", {
    "team": "str",
    "team_name": "str",
    "id": "str",
    "name": "str",
})

# CollaboratorDisconnectBody is a disconnect's body, which is empty: its path names the collaborator.
CollaboratorDisconnectBody = typing.TypedDict("CollaboratorDisconnectBody", {})

AgentCredential = typing.TypedDict("AgentCredential", {
    "credential": "str",
    "credential_id": "str",
    "machine": "str",
    "os_node": "str",
    "profile": "str",
    "iat": "int",
    "exp": "int",
    "renew_at": "int",
})

CursorClaims = typing.TypedDict("CursorClaims", {
    "v": "int",
    "tenant": "str",
    "workspace": "str | None",
    "feed_kind": "str",
    "feed": "str",
    "resource_kind": "str",
    "resource": "str",
    "filter": "str",
    "direction": "str",
    "recovery": "str",
    "position": "int",
})

# Offer is what one admitted attempt asks one machine to run
# (documentation/architecture/go-el2-capacity-design.md, decision 8). The bridge writes it to the
# machine's stream as the version-0 frame its kind names: ActionID is the frame's id, and RunID its
# run for a gate run, equal to ActionID otherwise.
Offer = typing.TypedDict("Offer", {
    "action_id": "str",
    "run_id": "str",
    "attempt_id": "str",
    "kind": "str",
    "work_kind": "str",
    "work_id": "str",
    "model_scope": "typing.NotRequired[str]",
    "harness": "typing.NotRequired[str]",
    "vendor": "str",
    "account_id": "str",
    "expires_at": "str",
    "gate": "typing.NotRequired[GateOffer | None]",
    "launch": "typing.NotRequired[LaunchOffer | None]",
})

# GateOffer pins the commission and the catalog row that this attempt was offered.
# Model is the launch selector; ExpectedModel is the separately observed receipt identity.
GateOffer = typing.TypedDict("GateOffer", {
    "commission": "str",
    "kind": "typing.NotRequired[str]",
    "repository": "str",
    "pr": "int",
    "branch": "typing.NotRequired[str]",
    "doc": "typing.NotRequired[str]",
    "head": "str",
    "base": "str",
    "round": "int",
    "cap": "int",
    "harness": "str",
    "tier": "str",
    "provider": "str",
    "model": "str",
    "expected_model": "str",
    "effort": "str",
    "deeper": "bool",
    "observation": "str",
    "policy_version": "int",
    "policy_digest": "str",
    "timeout": "int",
    "brief": "GateBrief",
})

# GateBrief is the incumbent gate runner's commission object. Knowledge stays empty until its
# owner's brief API supplies the block and the identities it contains.
GateBrief = typing.TypedDict("GateBrief", {
    "commission": "str",
    "kind": "str",
    "round": "int",
    "cap": "int",
    "repo": "str",
    "sha": "str",
    "base": "str",
    "pr": "int",
    "branch": "typing.NotRequired[str]",
    "doc": "typing.NotRequired[str]",
    "harness": "str",
    "prior": "list[GatePriorRound] | None",
    "knowledge": "str",
    "knowledge_ids": "list[str] | None",
})

GatePriorRound = typing.TypedDict("GatePriorRound", {
    "round": "int",
    "verdict": "str",
    "findings": "list[GatePriorFinding] | None",
})

GatePriorFinding = typing.TypedDict("GatePriorFinding", {
    "id": "str",
    "severity": "str",
    "file": "str",
    "line": "float",
    "claim": "str",
    "tag": "str",
    "lesson": "typing.NotRequired[str]",
    "status": "str",
})

# Stop asks that an attempt not run. A version-0 agent is sent nothing, so it settles server-side.
Stop = typing.TypedDict("Stop", {
    "attempt_id": "str",
})

# Receipt is a machine's report on an offer, in the wire's own states.
Receipt = typing.TypedDict("Receipt", {
    "action_id": "str",
    "run_id": "str",
    "state": "str",
    "session": "typing.NotRequired[ReceiptSession | None]",
    "report": "typing.NotRequired[typing.Any]",
})

# ReceiptSession is the session a launch's `session` answer names.
ReceiptSession = typing.TypedDict("ReceiptSession", {
    "id": "str",
    "epoch": "int",
})

# GateCarryBody asks that a pull request's passing review be carried to its new head. Equivalent
# is the author's word that the head is the reviewed change on a new base: it forces a replay and
# never waives one.
GateCarryBody = typing.TypedDict("GateCarryBody", {
    "repo": "str",
    "pr": "int",
    "head": "str",
    "equivalent": "bool",
})

# GateCarryAnswer is the carry recorded for the head, and the proof that admitted it.
GateCarryAnswer = typing.TypedDict("GateCarryAnswer", {
    "id": "str",
    "head": "str",
    "proof": "str",
    "replayed": "bool",
})

# GateLiftBody is a lift of a gate series by one round past its ceiling: the series as its gate keys
# it, a review's pull request or a critique's branch, the seat generation when the seat lifts, and
# its reason.
GateLiftBody = typing.TypedDict("GateLiftBody", {
    "kind": "str",
    "repo": "str",
    "pr": "typing.NotRequired[int]",
    "branch": "typing.NotRequired[str]",
    "generation": "typing.NotRequired[int]",
    "reason": "str",
})

# GateLiftAnswer is the lifted series and the rounds it may now run.
GateLiftAnswer = typing.TypedDict("GateLiftAnswer", {
    "series": "str",
    "cap": "int",
    "replayed": "bool",
})

# GateLostBody is what a machine reports of a gate run it gave up without an answer: the run, and
# what it kept of it. Commission is the offer's action id.
GateLostBody = typing.TypedDict("GateLostBody", {
    "uplink": "str",
    "commission": "str",
    "run": "str",
    "evidence": "typing.Any",
})

# GateLostAnswer names the run whose evidence is kept, as commission and run.
GateLostAnswer = typing.TypedDict("GateLostAnswer", {
    "kept": "list[str] | None",
})

# GateTokenBody asks for a read token for the repository of a gate run out on this machine. Scope
# is clone, the default, or review.
GateTokenBody = typing.TypedDict("GateTokenBody", {
    "uplink": "str",
    "commission": "str",
    "run": "str",
    "scope": "typing.NotRequired[str]",
})

# GateTokenAnswer is the token, and for a review the repository it reads: the reviewer's clone has
# no remote to name it.
GateTokenAnswer = typing.TypedDict("GateTokenAnswer", {
    "token": "str",
    "repo": "typing.NotRequired[str]",
})

# FactResource is the locator a resource's own route takes: a wire id where the resource has one,
# and the room a message is in.
FactResource = typing.TypedDict("FactResource", {
    "kind": "str",
    "id": "str",
    "room": "typing.NotRequired[str | None]",
})

Fact = typing.TypedDict("Fact", {
    "id": "str",
    "state": "str",
    "kind": "str",
    "v": "int",
    "ts": "str",
    "actor": "str",
    "resource": "FactResource",
})

# FactItem is api/pages.py's `{"at", "fact"}`.
FactItem = typing.TypedDict("FactItem", {
    "at": "int",
    "fact": "Fact",
})

FactsPage = typing.TypedDict("FactsPage", {
    "items": "list[FactItem] | None",
    "next": "str",
    "exhausted": "bool",
})

# GateRow is one commission, under the incumbent's wire names where it has them. By names the
# requesting session; Why is the commission's reason, or its result's; Findings counts the
# verdict's findings; Review is the published review's URL.
GateRow = typing.TypedDict("GateRow", {
    "id": "str",
    "kind": "str",
    "repo": "str",
    "pr": "int",
    "round": "int",
    "cap": "int",
    "final": "bool",
    "tier": "str",
    "harness": "str",
    "sha": "str",
    "base": "str",
    "by": "str",
    "commissioned_at": "str",
    "phase": "str",
    "why": "str | None",
    "verdict": "str | None",
    "findings": "int",
    "ended_at": "str | None",
    "review": "str | None",
    "reviewer": "GateReviewer | None",
    "run": "GateRun | None",
})

# GateReviewer is who the commission's attempt was given to, and, once judged, the model its
# receipt observed.
GateReviewer = typing.TypedDict("GateReviewer", {
    "vendor": "str",
    "account": "str",
    "model": "str | None",
    "model_source": "str | None",
})

# GateRun is the attempt's offer while it stands: when it was offered, delivered and is due.
GateRun = typing.TypedDict("GateRun", {
    "offered_at": "str",
    "delivered_at": "str | None",
    "deadline_at": "str",
})

# GateList answers GET /gates, newest commission first; Next asks for the page after it.
GateList = typing.TypedDict("GateList", {
    "items": "list[GateRow] | None",
    "next": "typing.NotRequired[str]",
})

# GateRead answers GET /gates/{gate}: the row, and its result once there is one.
GateRead = typing.TypedDict("GateRead", {
    "id": "str",
    "kind": "str",
    "repo": "str",
    "pr": "int",
    "round": "int",
    "cap": "int",
    "final": "bool",
    "tier": "str",
    "harness": "str",
    "sha": "str",
    "base": "str",
    "by": "str",
    "commissioned_at": "str",
    "phase": "str",
    "why": "str | None",
    "verdict": "str | None",
    "findings": "int",
    "ended_at": "str | None",
    "review": "str | None",
    "reviewer": "GateReviewer | None",
    "run": "GateRun | None",
    "result": "GateResult | None",
})

# GateResult is what the judge's receipt settled: a verdict with its findings, or unresolved with
# its reason. Declared is the verdict the judge gave where its findings derive another.
GateResult = typing.TypedDict("GateResult", {
    "state": "str",
    "verdict": "str | None",
    "declared": "str | None",
    "model": "str | None",
    "reason": "str | None",
    "findings": "list[GateFinding] | None",
})

GateFinding = typing.TypedDict("GateFinding", {
    "id": "str",
    "severity": "str",
    "file": "str",
    "line": "str",
    "claim": "str",
    "status": "str",
})

# GateStats answers GET /gates/stats: the open commissions by phase.
GateStats = typing.TypedDict("GateStats", {
    "open": "dict[str, int] | None",
})

KnowledgeUnit = typing.TypedDict("KnowledgeUnit", {
    "kind": "str",
    "id": "str",
    "scope": "list[str] | None",
    "status": "str",
    "source": "list[str] | None",
    "superseded_by": "typing.NotRequired[str]",
    "path": "str",
    "title": "typing.NotRequired[str]",
    "at": "str | None",
    "utc": "str | None",
})

KnowledgeSource = typing.TypedDict("KnowledgeSource", {
    "repo": "str | None",
    "index": "str | None",
    "commit": "str | None",
    "synced_at": "str | None",
    "how": "str | None",
})

KnowledgeDrift = typing.TypedDict("KnowledgeDrift", {
    "since": "str",
    "commit": "str",
    "reason": "str",
})

KnowledgeUnits = typing.TypedDict("KnowledgeUnits", {
    "items": "list[KnowledgeUnit] | None",
    "source": "KnowledgeSource",
    "stale": "bool",
    "drift": "KnowledgeDrift | None",
})

KnowledgeSyncBody = typing.TypedDict("KnowledgeSyncBody", {})

KnowledgeSyncAnswer = typing.TypedDict("KnowledgeSyncAnswer", {
    "sync": "str",
    "result": "str",
    "commit": "str | None",
    "changes": "typing.NotRequired[int | None]",
    "reason": "typing.NotRequired[str]",
})

# LaunchBody is the seat's launch: the harness to start and how, where when it names a machine or
# an account, and why. Go bounds each field and requires what the agent cannot start without.
LaunchBody = typing.TypedDict("LaunchBody", {
    "harness": "str",
    "machine": "typing.NotRequired[str | None]",
    "vendor": "typing.NotRequired[str]",
    "account": "typing.NotRequired[str]",
    "model": "typing.NotRequired[str]",
    "thinking": "typing.NotRequired[str]",
    "effort": "typing.NotRequired[str]",
    "window": "typing.NotRequired[bool]",
    "reason": "str",
})

# LaunchAnswer is the launch recorded and its request's state: admitted, its offer on its way to a
# machine, or waiting with the reason no machine took it yet.
LaunchAnswer = typing.TypedDict("LaunchAnswer", {
    "id": "str",
    "request": "str",
    "state": "str",
    "reason": "typing.NotRequired[str]",
    "replayed": "bool",
})

# LaunchOffer is how the offered launch starts its harness, as the seat asked.
LaunchOffer = typing.TypedDict("LaunchOffer", {
    "model": "typing.NotRequired[str]",
    "thinking": "typing.NotRequired[str]",
    "effort": "typing.NotRequired[str]",
    "window": "typing.NotRequired[bool]",
})

# MachineSample is one independently ordered machine fact. Value contains the validated JSON value.
MachineSample = typing.TypedDict("MachineSample", {
    "status": "str",
    "attempted_at": "str",
    "value": "typing.NotRequired[typing.Any]",
    "taken_at": "typing.NotRequired[str | None]",
    "reason": "typing.NotRequired[str]",
})

# MachineReport is the bounded v1 machine observation.
MachineReport = typing.TypedDict("MachineReport", {
    "v": "int",
    "inventory": "dict[str, MachineSample] | None",
    "readings": "dict[str, MachineSample] | None",
    "policy": "MachineSample",
})

# MachineReportBody is the native report body before admission binds its uplink.
MachineReportBody = typing.TypedDict("MachineReportBody", {
    "uplink": "str",
    "machine_report": "MachineReport",
})

MachineEvidence = typing.TypedDict("MachineEvidence", {
    "status": "str",
    "attempted_at": "str",
    "value": "typing.NotRequired[typing.Any]",
    "taken_at": "typing.NotRequired[str | None]",
    "reason": "typing.NotRequired[str]",
    "expires_at": "str | None",
    "historical": "bool",
    "alternatives": "typing.NotRequired[list[MachineEvidenceAlternative] | None]",
})

MachineEvidenceAlternative = typing.TypedDict("MachineEvidenceAlternative", {
    "registration": "str",
    "evidence": "MachineEvidence",
})

FleetProfile = typing.TypedDict("FleetProfile", {
    "registration": "str",
    "profile": "str",
})

FleetCensus = typing.TypedDict("FleetCensus", {
    "v": "int",
    "taken_at": "str",
    "total": "int",
    "unattributed": "int",
    "complete": "bool",
    "gaps": "list[str] | None",
    "expires_at": "str",
    "historical": "bool",
})

FleetCensusAlternative = typing.TypedDict("FleetCensusAlternative", {
    "registration": "str",
    "census": "FleetCensus",
})

FleetSource = typing.TypedDict("FleetSource", {
    "registrations": "list[str] | None",
    "profiles": "list[FleetProfile] | None",
    "inventory": "dict[str, MachineEvidence] | None",
    "readings": "dict[str, MachineEvidence] | None",
    "policy": "MachineEvidence | None",
    "worker_census": "FleetCensus | None",
    "worker_census_alternatives": "typing.NotRequired[list[FleetCensusAlternative] | None]",
})

FleetMachine = typing.TypedDict("FleetMachine", {
    "id": "str",
    "identity_scope": "str",
    "registrations": "list[str] | None",
    "sources": "list[FleetSource] | None",
})

MachineFleetPage = typing.TypedDict("MachineFleetPage", {
    "items": "list[FleetMachine] | None",
    "next": "str | None",
    "read_at": "str",
})

MachineReportAnswer = typing.TypedDict("MachineReportAnswer", {
    "status": "str",
})

ApproveDeviceRequest = typing.TypedDict("ApproveDeviceRequest", {
    "hardware": "str",
    "os_node": "str",
    "profile": "str",
    "reach": "str",
})

ExchangeDeviceRequest = typing.TypedDict("ExchangeDeviceRequest", {
    "hardware": "str",
    "os_node": "str",
})

DeviceApproval = typing.TypedDict("DeviceApproval", {
    "approval_id": "str",
    "secret": "str",
    "machine": "str",
    "os_node": "str",
    "profile": "str",
    "reach": "str",
    "iat": "int",
    "exp": "int",
})

RenewalProgress = typing.TypedDict("RenewalProgress", {
    "status": "str",
    "reason": "str",
    "recheck_at": "int",
})

# InstallationClaimBody connects GitHub for a team: the code GitHub handed back when its owner
# authorized the App, and the repository whose installation the owner administers. Verifier is
# the PKCE verifier when the authorization carried a challenge.
InstallationClaimBody = typing.TypedDict("InstallationClaimBody", {
    "code": "str",
    "verifier": "typing.NotRequired[str]",
    "repository": "str",
})

# InstallationClaimAnswer is the team's hold on the installation: newly "claimed", or already the
# team's ("held"), and the workspaces serving the repository that now read it as their source. A
# replay has no installation to name, and says so with Replayed.
InstallationClaimAnswer = typing.TypedDict("InstallationClaimAnswer", {
    "status": "str",
    "installation_id": "typing.NotRequired[int]",
    "repository": "typing.NotRequired[str]",
    "sources": "typing.NotRequired[list[str] | None]",
    "replayed": "typing.NotRequired[bool]",
})

# WorkspaceCreateBody installs a new repository for a team: the repository the workspace serves,
# which is its name, and the alias it is reached at, /w/<alias>.
WorkspaceCreateBody = typing.TypedDict("WorkspaceCreateBody", {
    "repository": "str",
    "alias": "str",
})

# WorkspaceCreateAnswer is the new workspace as access lists it, and its source: "registered" when
# the team already held the repository's installation, so the source is read from now; empty when
# Connect GitHub has yet to run for it.
WorkspaceCreateAnswer = typing.TypedDict("WorkspaceCreateAnswer", {
    "id": "str",
    "team_id": "str",
    "repo": "str",
    "source": "typing.NotRequired[str]",
    "replayed": "typing.NotRequired[bool]",
})

# TeamIntentBody is an operator's authorization of a team of one's own for a GitHub identity, which
# need not have signed up yet: its numeric id, and its login for display.
TeamIntentBody = typing.TypedDict("TeamIntentBody", {
    "github_id": "int",
    "login": "str",
})

# TeamIntentAnswer names the authorization, which the person's access lists as a "team" invitation.
TeamIntentAnswer = typing.TypedDict("TeamIntentAnswer", {
    "id": "str",
    "replayed": "typing.NotRequired[bool]",
})

# TeamCreateBody creates the team an authorization reserved for the caller, with its first
# workspace: the repository it serves is the workspace's name, reached at /w/<alias>.
TeamCreateBody = typing.TypedDict("TeamCreateBody", {
    "authorization": "str",
    "team_name": "str",
    "workspace_name": "str",
    "alias": "str",
})

# TeamCreateAnswer is the new team, of which the caller is the owner, and its first workspace.
TeamCreateAnswer = typing.TypedDict("TeamCreateAnswer", {
    "id": "str",
    "workspace": "WorkspaceDTO",
    "replayed": "typing.NotRequired[bool]",
})

# InstallationHeld says whether the team holds the App's installation on a repository, which is
# when its workspaces' sources can be read: what the install engine waits for after the owner is
# sent to Connect GitHub.
InstallationHeld = typing.TypedDict("InstallationHeld", {
    "held": "bool",
    "installation_id": "typing.NotRequired[int]",
    "repository": "typing.NotRequired[str]",
})

RoomAuthor = typing.TypedDict("RoomAuthor", {
    "kind": "str",
    "id": "str",
    "name": "typing.NotRequired[str | None]",
    "title": "typing.NotRequired[str | None]",
})

RoomRedaction = typing.TypedDict("RoomRedaction", {
    "by": "RoomAuthor",
    "at": "str",
})

# Room's CreatedBy is a RoomAuthor, or the string "platform" for the workspace's default room.
Room = typing.TypedDict("Room", {
    "id": "str",
    "name": "str",
    "default": "bool",
    "created_by": "typing.Any",
    "created_at": "str",
    "head": "int",
})

# RoomMessage's Text is null once redacted; ReplyTo and Act are absent when the message has none.
RoomMessage = typing.TypedDict("RoomMessage", {
    "id": "str",
    "seq": "int",
    "room": "str",
    "author": "RoomAuthor",
    "at": "str",
    "text": "str | None",
    "reply_to": "typing.NotRequired[str | None]",
    "act": "typing.NotRequired[typing.Any]",
    "redacted": "RoomRedaction | None",
})

RoomRequest = typing.TypedDict("RoomRequest", {
    "id": "str",
    "state": "str",
    "requester": "RoomAuthor",
    "addressee": "RoomAuthor",
    "acceptance": "str",
    "last_seq": "int",
})

# RoomPage is messages oldest first. Next pages forward, Before back and is null at the room's
# start; Head is true when nothing newer is committed.
RoomPage = typing.TypedDict("RoomPage", {
    "items": "list[RoomMessage] | None",
    "next": "str",
    "before": "str | None",
    "head": "bool",
})

# SayBody is the body of POST /sessions/{session}/says (go-session-say-design.md decision 7): the
# speaker's own occurrence, the session it speaks to (none for the brain) and its words.
SayBody = typing.TypedDict("SayBody", {
    "occurrence": "str",
    "to": "typing.NotRequired[str]",
    "text": "str",
})

# SayAnswer is where a say went: `sent` to a session at its epoch, or `unheard`, kept on the
# brain's queue as the need its id names because nobody holds the seat.
SayAnswer = typing.TypedDict("SayAnswer", {
    "id": "str",
    "state": "str",
    "to": "typing.NotRequired[str]",
    "epoch": "typing.NotRequired[int]",
})

# SayReceipt is the agent's report that a say it was written is in its session's hands.
SayReceipt = typing.TypedDict("SayReceipt", {
    "session": "str",
    "id": "str",
})

# SayReceiptAnswer says whether the say is settled: false when it lapsed first.
SayReceiptAnswer = typing.TypedDict("SayReceiptAnswer", {
    "session": "str",
    "id": "str",
    "received": "bool",
})

# DetachExit is why a session left, kept with the epoch it ended (doc 123 §4): a handover's
# checkpoint URL, or a one-line reason it abandoned or retired.
DetachExit = typing.TypedDict("DetachExit", {
    "kind": "str",
    "text": "str",
})

# DetachBody is a detachment's body: empty, or why the session left, as an exit's kind and text.
DetachBody = typing.TypedDict("DetachBody", {
    "exit": "typing.NotRequired[str]",
    "text": "typing.NotRequired[str]",
})

# SessionCredential is the token a session enrolment issues, rendered once to the enrolling
# machine and again only to its recovery proof.
SessionCredential = typing.TypedDict("SessionCredential", {
    "credential": "str",
    "credential_id": "str",
    "epoch": "int",
})

# SessionList is GET /sessions: the workspace's sessions at their current epochs, by name.
SessionList = typing.TypedDict("SessionList", {
    "items": "list[ListedSession] | None",
})

# ListedSession is one session on the fleet. Machine is the registration holding it. Status is
# what the session last said, at the epoch it said it, or nil when it has said nothing. Observed is
# what its machine saw this epoch run, newest first. Cards are the live cards it executes at this
# epoch, by wire id, first engaged first.
ListedSession = typing.TypedDict("ListedSession", {
    "name": "str",
    "epoch": "int",
    "state": "str",
    "machine": "str",
    "machine_registration": "str",
    "enrolled_at": "str",
    "status": "ListedStatus | None",
    "observed": "list[ObservedReport] | None",
    "cards": "list[str] | None",
})

# ObservedReport is one model a session's machine observed it run. Vendor is its maker, empty when
# the model names none; a client draws it and never derives one.
ObservedReport = typing.TypedDict("ObservedReport", {
    "model": "str",
    "provider": "str",
    "vendor": "str",
    "observed_at": "str",
})

# ListedStatus is a session's folded status as the fleet reads it.
ListedStatus = typing.TypedDict("ListedStatus", {
    "epoch": "int",
    "work": "str | None",
    "on": "str | None",
    "blocked_on": "str | None",
    "done": "str | None",
    "at": "str",
})

# SourceState is what the board is told of a source: when it was last read whole or in part,
# whether a failure since has made it stale and why, whether its last good read is past its expiry,
# and the gaps that read left. A source is named by its UUID.
SourceState = typing.TypedDict("SourceState", {
    "id": "str",
    "repository": "str",
    "swept": "str | None",
    "stale": "bool",
    "stale_because": "str | None",
    "expired": "bool",
    "partial": "bool",
    "gaps": "list[str] | None",
})

# SessionStatus is what a session says of itself (steering/verb_grammar.py parse_status): announce
# what it is doing, and on which branch; blocked, by what; done, with what. The incumbent's line
# says `on` for both a branch and a blocker; the wire names them apart.
#
# An announce's repo is the repository its branch is in, which binds the branch to the card the
# session executes; its harness and account are the incumbent's `as <harness>/<account>`, a claim
# shown as one and never trusted (go-el1a-work-design.md §10).
SessionStatus = typing.TypedDict("SessionStatus", {
    "state": "str",
    "doing": "typing.NotRequired[str]",
    "branch": "typing.NotRequired[str]",
    "repo": "typing.NotRequired[str]",
    "harness": "typing.NotRequired[str]",
    "account": "typing.NotRequired[str]",
    "blocker": "typing.NotRequired[str]",
    "what": "typing.NotRequired[str]",
})

# StreamFeed is one feed a stream follows and the position it has reached on it.
StreamFeed = typing.TypedDict("StreamFeed", {
    "kind": "str",
    "id": "str",
    "position": "int",
})

# StreamCursor is where a stream stands on every feed it follows, at once: a snapshot answers
# one, each event carries the next, and a reconnect sends the last it received.
StreamCursor = typing.TypedDict("StreamCursor", {
    "v": "int",
    "kind": "str",
    "tenant": "str",
    "workspace": "str",
    "recovery": "str",
    "feeds": "list[StreamFeed] | None",
})

# SnapshotFeed is a feed as a client names it, `workspace` or `room:<rm_…>`, and its head.
SnapshotFeed = typing.TypedDict("SnapshotFeed", {
    "feed": "str",
    "position": "int",
})

SnapshotSession = typing.TypedDict("SnapshotSession", {
    "name": "str",
    "epoch": "int",
    "state": "str",
})

SnapshotSections = typing.TypedDict("SnapshotSections", {
    "rooms": "list[Room] | None",
    "sessions": "typing.NotRequired[list[SnapshotSession] | None]",
    "machines": "typing.NotRequired[MachineFleetPage | None]",
})

SnapshotProvenance = typing.TypedDict("SnapshotProvenance", {
    "recovery_epoch": "str",
    "read_at": "str",
})

# StreamEvent is a fact event's data on the workspace feed (`GET …/events`): one entry of a feed,
# rendered as /facts renders it.
StreamEvent = typing.TypedDict("StreamEvent", {
    "feed": "str",
    "position": "int",
    "fact": "Fact",
})

# Snapshot is the workspace's state and the cursor that resumes after it, read in one transaction.
Snapshot = typing.TypedDict("Snapshot", {
    "sections": "SnapshotSections",
    "feeds": "list[SnapshotFeed] | None",
    "cursor": "str",
    "provenance": "SnapshotProvenance",
})

# SessionWait is what a session waits for (steering/verb_grammar.py parse_status): a pull
# request's merge or its next gate verdict, or a time; told once it holds, or at its recheck
# that it has not. Recheck 0 is the default.
SessionWait = typing.TypedDict("SessionWait", {
    "kind": "str",
    "repo": "typing.NotRequired[str]",
    "pr": "typing.NotRequired[int]",
    "at": "typing.NotRequired[str]",
    "recheck": "typing.NotRequired[int]",
})

# WaitAnswer names the wait registered.
WaitAnswer = typing.TypedDict("WaitAnswer", {
    "id": "str",
})

IntentCreateBody = typing.TypedDict("IntentCreateBody", {
    "title": "str",
    "context": "typing.NotRequired[str]",
})

IntentDispositionBody = typing.TypedDict("IntentDispositionBody", {
    "disposition": "str",
    "reason": "str",
})

IssueRef = typing.TypedDict("IssueRef", {
    "repo": "str",
    "n": "int",
})

AnchorBody = typing.TypedDict("AnchorBody", {
    "verb": "str",
    "repo": "str",
    "n": "int",
})

BranchBody = typing.TypedDict("BranchBody", {
    "repo": "str",
    "branch": "str",
})

# CardCreateBody makes a card. ID is the client's own 24-hex id when it minted one.
CardCreateBody = typing.TypedDict("CardCreateBody", {
    "id": "typing.NotRequired[str]",
    "name": "str",
    "major": "typing.NotRequired[bool]",
    "intents": "typing.NotRequired[list[str] | None]",
    "anchors": "typing.NotRequired[list[AnchorBody] | None]",
    "track": "typing.NotRequired[str]",
})

# AssociationBody names one anchor or one branch. A dissociation says why.
AssociationBody = typing.TypedDict("AssociationBody", {
    "anchor": "typing.NotRequired[AnchorBody | None]",
    "branch": "typing.NotRequired[BranchBody | None]",
    "why": "typing.NotRequired[str]",
})

# EngagementBody names a session of the workspace. A disengagement says why.
EngagementBody = typing.TypedDict("EngagementBody", {
    "session": "str",
    "role": "typing.NotRequired[str]",
    "why": "typing.NotRequired[str]",
})

# LinkBody names exactly one target: a card by its id, or an issue.
LinkBody = typing.TypedDict("LinkBody", {
    "kind": "str",
    "to_card": "typing.NotRequired[str]",
    "to_issue": "typing.NotRequired[IssueRef | None]",
    "to_goal": "typing.NotRequired[str]",
    "why": "str",
    "source": "typing.NotRequired[str]",
})

UnlinkBody = typing.TypedDict("UnlinkBody", {
    "kind": "str",
    "to_card": "typing.NotRequired[str]",
    "to_issue": "typing.NotRequired[IssueRef | None]",
    "to_goal": "typing.NotRequired[str]",
    "how": "str",
    "why": "str",
})

ConclusionBody = typing.TypedDict("ConclusionBody", {
    "evidence": "typing.NotRequired[str]",
    "keep_branch": "typing.NotRequired[bool]",
})

CorrectionBody = typing.TypedDict("CorrectionBody", {
    "field": "str",
    "after": "str",
    "why": "str",
})

RetirementBody = typing.TypedDict("RetirementBody", {
    "why": "str",
})

# UnconclusionBody takes back a card's conclusion, saying why, as every ending does.
UnconclusionBody = typing.TypedDict("UnconclusionBody", {
    "why": "str",
})

# RevivalBody takes a card the keeper retired back to live.
RevivalBody = typing.TypedDict("RevivalBody", {
    "why": "str",
})

# TrackBody declares a card's lane, by id, or "off-track" for repository upkeep.
TrackBody = typing.TypedDict("TrackBody", {
    "track": "str",
    "why": "str",
})

# WorkActor is who a transition records: `owner` for a member, or the `seat` or a `session` by
# the session's name.
WorkActor = typing.TypedDict("WorkActor", {
    "kind": "str",
    "session": "typing.NotRequired[str]",
})

WorkEnding = typing.TypedDict("WorkEnding", {
    "by": "WorkActor",
    "at": "str",
    "why": "str",
})

IntentDTO = typing.TypedDict("IntentDTO", {
    "id": "str",
    "title": "str",
    "context": "str",
    "disposition": "str",
    "by": "WorkActor",
    "at": "str",
    "disposed": "typing.NotRequired[WorkEnding | None]",
    "cards": "list[str] | None",
})

AnchorDTO = typing.TypedDict("AnchorDTO", {
    "verb": "str",
    "repo": "str",
    "n": "int",
    "by": "WorkActor",
    "at": "str",
    "ended": "typing.NotRequired[WorkEnding | None]",
})

BranchDTO = typing.TypedDict("BranchDTO", {
    "repo": "str",
    "branch": "str",
    "by": "WorkActor",
    "at": "str",
    "ended": "typing.NotRequired[WorkEnding | None]",
})

AliasDTO = typing.TypedDict("AliasDTO", {
    "kind": "str",
    "repo": "str",
    "value": "str",
})

ExecutorDTO = typing.TypedDict("ExecutorDTO", {
    "session": "str",
    "role": "str",
    "epoch": "int",
    "live": "bool",
    "by": "WorkActor",
    "at": "str",
    "ended": "typing.NotRequired[WorkEnding | None]",
})

CorrectionDTO = typing.TypedDict("CorrectionDTO", {
    "field": "str",
    "before": "str",
    "after": "str",
    "by": "WorkActor",
    "at": "str",
    "why": "str",
})

ConclusionDTO = typing.TypedDict("ConclusionDTO", {
    "evidence": "typing.NotRequired[str]",
    "keep_branch": "bool",
    "by": "WorkActor",
    "at": "str",
})

UnlinkedDTO = typing.TypedDict("UnlinkedDTO", {
    "by": "WorkActor",
    "at": "str",
    "how": "str",
    "why": "str",
})

# LinkDTO is a link the card declared, live or ended: its own history. On, and each card or issue
# the board names, is a card's id or an issue as owner/repo#n.
LinkDTO = typing.TypedDict("LinkDTO", {
    "kind": "str",
    "on": "str",
    "why": "str",
    "source": "typing.NotRequired[str]",
    "by": "WorkActor",
    "at": "str",
    "ended": "typing.NotRequired[UnlinkedDTO | None]",
})

# CardDTO is a card's own recorded state. What other cards and the forge make of it is its Board.
CardDTO = typing.TypedDict("CardDTO", {
    "id": "str",
    "name": "str",
    "major": "bool",
    "state": "str",
    "track": "typing.NotRequired[str]",
    "by": "WorkActor",
    "at": "str",
    "retired": "typing.NotRequired[WorkEnding | None]",
    "intents": "list[str] | None",
    "anchors": "list[AnchorDTO] | None",
    "branches": "list[BranchDTO] | None",
    "aliases": "list[AliasDTO] | None",
    "executors": "list[ExecutorDTO] | None",
    "links": "list[LinkDTO] | None",
    "corrections": "list[CorrectionDTO] | None",
    "conclusion": "typing.NotRequired[ConclusionDTO | None]",
    "board": "BoardDTO",
})

# DepDTO is one live prerequisite as the board reads it now: declared or observed, and open.
DepDTO = typing.TypedDict("DepDTO", {
    "on": "str",
    "provenance": "str",
    "open": "bool",
    "to": "typing.NotRequired[list[str] | None]",
    "at": "str",
})

AnomalyDTO = typing.TypedDict("AnomalyDTO", {
    "kind": "str",
    "detail": "str",
})

# BoardDTO is what the card's state means beside every other card's and the forge's, folded at
# AsOf: the workspace feed's head in the same read. A source's observation publishes no feed entry
# before EL5, so the board can move while AsOf does not.
BoardDTO = typing.TypedDict("BoardDTO", {
    "as_of": "int",
    "deps": "list[DepDTO] | None",
    "waiting": "bool",
    "waiting_since": "str | None",
    "fanout": "int",
    "unsourced": "list[str] | None",
    "anomalies": "list[AnomalyDTO] | None",
    "ending": "typing.NotRequired[str]",
    "executing": "list[str] | None",
})

# IntentAnswer and CardAnswer are a work command's answer: the resource as it stands after it,
# whether the request was a retry answered from its first attempt, and the workspace feed position
# its transition was published at; 0 when it changed nothing.
IntentAnswer = typing.TypedDict("IntentAnswer", {
    "intent": "IntentDTO",
    "replayed": "bool",
    "position": "int",
})

CardAnswer = typing.TypedDict("CardAnswer", {
    "card": "CardDTO",
    "replayed": "bool",
    "position": "int",
})

# IntentRead and CardRead answer a read.
IntentRead = typing.TypedDict("IntentRead", {
    "intent": "IntentDTO",
})

CardRead = typing.TypedDict("CardRead", {
    "card": "CardDTO",
})

# CardList and IntentList answer a list read: a page, and Next to ask for the one after it, absent
# on the last.
CardList = typing.TypedDict("CardList", {
    "cards": "list[CardDTO] | None",
    "next": "typing.NotRequired[str]",
})

# TracksRead is a workspace's tracks: the document it binds, its live lanes in the document's order
# with each lane's definition, the document's other settings, and how its syncs stand.
TracksRead = typing.TypedDict("TracksRead", {
    "repo": "str",
    "path": "str",
    "lanes": "list[LaneDTO] | None",
    "settings": "typing.Any",
    "synced": "TracksSynced | None",
    "failed": "TracksFailed | None",
    "awaited": "TracksAwaited | None",
    "off_track": "CardTally",
})

LaneDTO = typing.TypedDict("LaneDTO", {
    "id": "str",
    "name": "str",
    "definition": "typing.Any",
    "cards": "CardTally",
})

# CardTally is how many standing cards are live and how many have concluded, read with the lanes so
# a lane's head needs no page of either list.
CardTally = typing.TypedDict("CardTally", {
    "live": "int",
    "concluded": "int",
})

TracksSynced = typing.TypedDict("TracksSynced", {
    "commit": "str",
    "at": "str",
})

TracksFailed = typing.TypedDict("TracksFailed", {
    "commit": "str",
    "reason": "str",
    "since": "str",
})

TracksAwaited = typing.TypedDict("TracksAwaited", {
    "commit": "str",
})

IntentList = typing.TypedDict("IntentList", {
    "intents": "list[IntentDTO] | None",
    "next": "typing.NotRequired[str]",
})

# WorkProblem is a refusal as both carriers answer it: the check that refused, and the body field
# it refused when it was one.
WorkProblem = typing.TypedDict("WorkProblem", {
    "type": "str",
    "status": "int",
    "code": "str",
    "field": "typing.NotRequired[str]",
})

# SourceBody registers the repository a workspace reads, through the App installation its team
# holds.
SourceBody = typing.TypedDict("SourceBody", {
    "repo": "str",
    "installation": "int",
})

# SourceAnswer names the source a registration made, or the live one that already reads the
# repository. Position is 0 when the registration published nothing.
SourceAnswer = typing.TypedDict("SourceAnswer", {
    "source": "str",
    "status": "str",
    "replayed": "bool",
    "position": "int",
})

# TracksBindBody binds the workspace's tracks to a document in a repository it reads; the path
# defaults to the tracks document's conventional place.
TracksBindBody = typing.TypedDict("TracksBindBody", {
    "repo": "str",
    "path": "typing.NotRequired[str]",
})

# TracksBindAnswer is the binding as written.
TracksBindAnswer = typing.TypedDict("TracksBindAnswer", {
    "status": "str",
    "replayed": "bool",
    "position": "int",
})

# WorkRoute is one route of the work wire: its method and path under WorkBase, the query form that
# selects it when one path answers several, and the names of its request body and answer in
# testdata/work.json; a read has no request.
WorkRoute = typing.TypedDict("WorkRoute", {
    "method": "str",
    "path": "str",
    "query": "typing.NotRequired[str]",
    "request": "typing.NotRequired[str]",
    "answer": "str",
})

# WorkerCensus is the bounded aggregate worker observation. It carries no worker or session identity.
WorkerCensus = typing.TypedDict("WorkerCensus", {
    "v": "int",
    "taken_at": "str",
    "total": "int",
    "unattributed": "int",
    "complete": "bool",
    "gaps": "list[str] | None",
})

# WorkerCensusBody is the native census body before admission binds its uplink.
WorkerCensusBody = typing.TypedDict("WorkerCensusBody", {
    "uplink": "str",
    "worker_census": "WorkerCensus",
})

# Every route serve mounts, by its pattern.
ROUTES = frozenset({
    "GET /api/v1/access",
    "GET /api/v1/csrf",
    "POST /api/v1/team-authorizations",
    "POST /api/v1/teams",
    "GET /api/v1/teams/{team}/collaborators",
    "POST /api/v1/teams/{team}/collaborators",
    "POST /api/v1/teams/{team}/collaborators/{collaborator}/disable",
    "POST /api/v1/teams/{team}/collaborators/{collaborator}/disconnection",
    "POST /api/v1/teams/{team}/collaborators/{collaborator}/grants",
    "POST /api/v1/teams/{team}/collaborators/{collaborator}/grants/{grant}/narrowing",
    "POST /api/v1/teams/{team}/collaborators/{collaborator}/grants/{grant}/revocation",
    "POST /api/v1/teams/{team}/collaborators/{collaborator}/title",
    "GET /api/v1/teams/{team}/installations",
    "POST /api/v1/teams/{team}/installations",
    "POST /api/v1/teams/{team}/invitations",
    "POST /api/v1/teams/{team}/invitations/{invitation}/redeem",
    "POST /api/v1/teams/{team}/workspaces",
    "POST /forge/hook",
    "GET /healthz",
    "GET /w/{workspace}/api/v1/board",
    "GET /w/{workspace}/api/v1/brain/requests",
    "POST /w/{workspace}/api/v1/brain/requests",
    "GET /w/{workspace}/api/v1/brain/requests/{request}",
    "POST /w/{workspace}/api/v1/brain/requests/{request}/answer",
    "GET /w/{workspace}/api/v1/cards",
    "POST /w/{workspace}/api/v1/cards",
    "GET /w/{workspace}/api/v1/cards/{card}",
    "POST /w/{workspace}/api/v1/cards/{card}/associations",
    "GET /w/{workspace}/api/v1/cards/{card}/checkpoints",
    "POST /w/{workspace}/api/v1/cards/{card}/conclusion",
    "POST /w/{workspace}/api/v1/cards/{card}/corrections",
    "POST /w/{workspace}/api/v1/cards/{card}/disengagements",
    "POST /w/{workspace}/api/v1/cards/{card}/dissociations",
    "POST /w/{workspace}/api/v1/cards/{card}/engagements",
    "POST /w/{workspace}/api/v1/cards/{card}/links",
    "POST /w/{workspace}/api/v1/cards/{card}/retirement",
    "POST /w/{workspace}/api/v1/cards/{card}/revival",
    "POST /w/{workspace}/api/v1/cards/{card}/track",
    "POST /w/{workspace}/api/v1/cards/{card}/unconclusion",
    "POST /w/{workspace}/api/v1/cards/{card}/unlinks",
    "POST /w/{workspace}/api/v1/checkpoints",
    "GET /w/{workspace}/api/v1/checkpoints/{checkpoint}",
    "GET /w/{workspace}/api/v1/collaborator",
    "POST /w/{workspace}/api/v1/credentials/{credential}/revocations",
    "POST /w/{workspace}/api/v1/device-approvals",
    "POST /w/{workspace}/api/v1/device-exchanges",
    "GET /w/{workspace}/api/v1/events",
    "GET /w/{workspace}/api/v1/facts",
    "GET /w/{workspace}/api/v1/gates",
    "POST /w/{workspace}/api/v1/gates",
    "POST /w/{workspace}/api/v1/gates/carries",
    "POST /w/{workspace}/api/v1/gates/lifts",
    "GET /w/{workspace}/api/v1/gates/stats",
    "GET /w/{workspace}/api/v1/gates/{gate}",
    "POST /w/{workspace}/api/v1/gates/{gate}/cancellation",
    "POST /w/{workspace}/api/v1/incarnations",
    "GET /w/{workspace}/api/v1/intents",
    "POST /w/{workspace}/api/v1/intents",
    "GET /w/{workspace}/api/v1/intents/{intent}",
    "POST /w/{workspace}/api/v1/intents/{intent}/disposition",
    "POST /w/{workspace}/api/v1/knowledge/syncs",
    "GET /w/{workspace}/api/v1/knowledge/units",
    "GET /w/{workspace}/api/v1/knowledge/units/{id}",
    "POST /w/{workspace}/api/v1/launches",
    "POST /w/{workspace}/api/v1/machine-renewals",
    "GET /w/{workspace}/api/v1/machines",
    "POST /w/{workspace}/api/v1/names",
    "GET /w/{workspace}/api/v1/needs",
    "POST /w/{workspace}/api/v1/needs",
    "POST /w/{workspace}/api/v1/needs/{need}/transitions",
    "GET /w/{workspace}/api/v1/rooms",
    "POST /w/{workspace}/api/v1/rooms",
    "GET /w/{workspace}/api/v1/rooms/{room}",
    "GET /w/{workspace}/api/v1/rooms/{room}/messages",
    "POST /w/{workspace}/api/v1/rooms/{room}/messages",
    "GET /w/{workspace}/api/v1/rooms/{room}/messages/{message}",
    "POST /w/{workspace}/api/v1/rooms/{room}/messages/{message}/redaction",
    "GET /w/{workspace}/api/v1/rooms/{room}/requests",
    "GET /w/{workspace}/api/v1/rulings",
    "POST /w/{workspace}/api/v1/rulings/{ruling}/transitions",
    "GET /w/{workspace}/api/v1/seat",
    "POST /w/{workspace}/api/v1/seat/appointment",
    "POST /w/{workspace}/api/v1/seat/release",
    "GET /w/{workspace}/api/v1/sessions",
    "POST /w/{workspace}/api/v1/sessions",
    "POST /w/{workspace}/api/v1/sessions/{session}/bindings",
    "POST /w/{workspace}/api/v1/sessions/{session}/detachment",
    "POST /w/{workspace}/api/v1/sessions/{session}/directives",
    "POST /w/{workspace}/api/v1/sessions/{session}/directives/{directive}/acknowledgement",
    "POST /w/{workspace}/api/v1/sessions/{session}/says",
    "POST /w/{workspace}/api/v1/sessions/{session}/seat/acquisition",
    "POST /w/{workspace}/api/v1/sessions/{session}/seat/handover",
    "POST /w/{workspace}/api/v1/sessions/{session}/seat/release",
    "POST /w/{workspace}/api/v1/sessions/{session}/seat/renewal",
    "POST /w/{workspace}/api/v1/sessions/{session}/status",
    "POST /w/{workspace}/api/v1/sessions/{session}/waits",
    "GET /w/{workspace}/api/v1/snapshot",
    "POST /w/{workspace}/api/v1/sources",
    "GET /w/{workspace}/api/v1/tracks",
    "POST /w/{workspace}/api/v1/tracks",
    "POST /w/{workspace}/steering/agent/accounts",
    "POST /w/{workspace}/steering/agent/census",
    "POST /w/{workspace}/steering/agent/facts",
    "POST /w/{workspace}/steering/agent/gate",
    "POST /w/{workspace}/steering/agent/gate/lost",
    "POST /w/{workspace}/steering/agent/gate/token",
    "POST /w/{workspace}/steering/agent/hold",
    "POST /w/{workspace}/steering/agent/injected",
    "POST /w/{workspace}/steering/agent/injection",
    "POST /w/{workspace}/steering/agent/judges",
    "POST /w/{workspace}/steering/agent/launch",
    "GET /w/{workspace}/steering/agent/package/{sha}",
    "POST /w/{workspace}/steering/agent/reach",
    "POST /w/{workspace}/steering/agent/reading",
    "POST /w/{workspace}/steering/agent/received",
    "POST /w/{workspace}/steering/agent/release",
    "POST /w/{workspace}/steering/agent/renew",
    "GET /w/{workspace}/steering/agent/stream",
    "GET /w/{workspace}/steering/agent/target",
    "POST /w/{workspace}/steering/agent/undelivered",
    "POST /w/{workspace}/steering/agent/watch",
    "GET /w/{workspace}/steering/authorities",
    "POST /w/{workspace}/steering/door",
    "POST /w/{workspace}/steering/observe",
})


def path(route: str, **params: str) -> str:
    """The path a route of ROUTES answers at, each of its parameters filled and escaped."""
    if route not in ROUTES:
        raise ValueError(f"{route!r} is not a route serve mounts")
    out = []
    for segment in route.split(" ", 1)[1].split("/"):
        if segment.startswith("{") and segment.endswith("}"):
            name = segment[1:-1]
            if name not in params:
                raise ValueError(f"{route!r} needs {name}")
            segment = urllib.parse.quote(str(params.pop(name)), safe="")
        out.append(segment)
    if params:
        raise ValueError(f"{route!r} has no parameter {', '.join(sorted(params))}")
    return "/".join(out)
